// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAONGdFRJWaVlkK6eGXcaKommdYZFm52I',
    appId: '1:861765225777:web:cb7ea652d70c0a7ec6f410',
    messagingSenderId: '861765225777',
    projectId: 'finmate-7788a',
    authDomain: 'finmate-7788a.firebaseapp.com',
    storageBucket: 'finmate-7788a.firebasestorage.app',
    measurementId: 'G-J0LQLGV1KQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbmS0v_4ZVqLZ3B7u1gD0Nnytna2Fj8Nw',
    appId: '1:861765225777:android:84d57503d3bcae8bc6f410',
    messagingSenderId: '861765225777',
    projectId: 'finmate-7788a',
    storageBucket: 'finmate-7788a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeA31GvfAmF9wkB6SrXL5AAhE49li3RE0',
    appId: '1:861765225777:ios:85335c55b81d4ac0c6f410',
    messagingSenderId: '861765225777',
    projectId: 'finmate-7788a',
    storageBucket: 'finmate-7788a.firebasestorage.app',
    iosBundleId: 'com.example.finmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeA31GvfAmF9wkB6SrXL5AAhE49li3RE0',
    appId: '1:861765225777:ios:85335c55b81d4ac0c6f410',
    messagingSenderId: '861765225777',
    projectId: 'finmate-7788a',
    storageBucket: 'finmate-7788a.firebasestorage.app',
    iosBundleId: 'com.example.finmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAONGdFRJWaVlkK6eGXcaKommdYZFm52I',
    appId: '1:861765225777:web:c85cfe187b104594c6f410',
    messagingSenderId: '861765225777',
    projectId: 'finmate-7788a',
    authDomain: 'finmate-7788a.firebaseapp.com',
    storageBucket: 'finmate-7788a.firebasestorage.app',
    measurementId: 'G-5MMTD32TW6',
  );
}
